### ISSUE TITLE
More

### ISSUE THREAD

**Issue by Deadlineem** [YimMenu-Lua/Singleplayer-Menu#1]
From Extras Addon to you

`

    mCash = 0
    StoryCharacters:add_imgui(function()
        mCash, used = ImGui.SliderInt("Michael's Cash", mCash, 1, 2147483646)
        out = "Michael's cash set to $"..tostring(mCash)
        if used then
            STATS.STAT_SET_INT(joaat("SP0_TOTAL_CASH"), mCash, true)
            gui.show_message('Story Mode Cash Updated!', out)
        end
    end)

    fCash = 0
    StoryCharacters:add_imgui(function()
        fCash, used = ImGui.SliderInt("Franklin's Cash", fCash, 1, 2147483646)
        out = "Franklins's cash set to $"..tostring(fCash)
        if used then
            STATS.STAT_SET_INT(joaat("SP1_TOTAL_CASH"), fCash, true)
            gui.show_message('Story Mode Cash Updated!', out)
        end
    end)

    tCash = 0
    StoryCharacters:add_imgui(function()
        tCash, used = ImGui.SliderInt("Trevor's Cash", tCash, 1, 2147483646)
        out = "Trevor's cash set to $"..tostring(tCash)
        if used then
            STATS.STAT_SET_INT(joaat("SP2_TOTAL_CASH"), tCash, true)
            gui.show_message('Story Mode Cash Updated!', out)
        end
    end)
    StoryCharacters:add_separator()
    mStats = 0
    StoryCharacters:add_imgui(function()
        mStats, used = ImGui.SliderInt("Michael's Stats", mStats, 0, 100)
        out = "Michael's Stats set to "..tostring(mStats).."/100"
        if used then
            STATS.STAT_SET_INT(joaat("SP0_SPECIAL_ABILITY"), mStats, true)
            STATS.STAT_SET_INT(joaat("SP0_STAMINA"), mStats, true)
            STATS.STAT_SET_INT(joaat("SP0_STRENGTH"), mStats, true)
            STATS.STAT_SET_INT(joaat("SP0_LUNG_CAPACITY"), mStats, true)
            STATS.STAT_SET_INT(joaat("SP0_WHEELIE_ABILITY"), mStats, true)
            STATS.STAT_SET_INT(joaat("SP0_FLYING_ABILITY"), mStats, true)
            STATS.STAT_SET_INT(joaat("SP0_SHOOTING_ABILITY"), mStats, true)
            STATS.STAT_SET_INT(joaat("SP0_STEALTH_ABILITY"), mStats, true)
            gui.show_message('Story Mode Stats Updated!', out)
        end
    end)

    fStats = 0
    StoryCharacters:add_imgui(function()
        fStats, used = ImGui.SliderInt("Franklin's Stats", fStats, 0, 100)
        out = "Franklin's Stats set to "..tostring(fStats).."/100"
        if used then
            STATS.STAT_SET_INT(joaat("SP1_SPECIAL_ABILITY"), fStats, true)
            STATS.STAT_SET_INT(joaat("SP1_STAMINA"), fStats, true)
            STATS.STAT_SET_INT(joaat("SP1_STRENGTH"), fStats, true)
            STATS.STAT_SET_INT(joaat("SP1_LUNG_CAPACITY"), fStats, true)
            STATS.STAT_SET_INT(joaat("SP1_WHEELIE_ABILITY"), fStats, true)
            STATS.STAT_SET_INT(joaat("SP1_FLYING_ABILITY"), fStats, true)
            STATS.STAT_SET_INT(joaat("SP1_SHOOTING_ABILITY"), fStats, true)
            STATS.STAT_SET_INT(joaat("SP1_STEALTH_ABILITY"), fStats, true)
            gui.show_message('Story Mode Stats Updated!', out)
        end
    end)

    tStats = 0
    StoryCharacters:add_imgui(function()
        tStats, used = ImGui.SliderInt("Trevor's Stats", tStats, 0, 100)
        out = "Trevor's Stats set to "..tostring(tStats).."/100"
        if used then
            STATS.STAT_SET_INT(joaat("SP2_SPECIAL_ABILITY"), tStats, true)
            STATS.STAT_SET_INT(joaat("SP2_STAMINA"), tStats, true)
            STATS.STAT_SET_INT(joaat("SP2_STRENGTH"), tStats, true)
            STATS.STAT_SET_INT(joaat("SP2_LUNG_CAPACITY"), tStats, true)
            STATS.STAT_SET_INT(joaat("SP2_WHEELIE_ABILITY"), tStats, true)
            STATS.STAT_SET_INT(joaat("SP2_FLYING_ABILITY"), tStats, true)
            STATS.STAT_SET_INT(joaat("SP2_SHOOTING_ABILITY"), tStats, true)
            STATS.STAT_SET_INT(joaat("SP2_STEALTH_ABILITY"), tStats, true)
            gui.show_message('Story Mode Stats Updated!', out)
        end
    end)`
    
The money option is a slider to set the amount of money for each SP character, rather than just adding 1 million here and there and also SP stats sliders.  Feel free to change this all to your liking, probably alot of unnecessary extra code since this does not have a SP switch like the current script you provided has.

**Comment by L7NEG** [comment]
> From Extras Addon to you
> 
> `
> 
> ```
> mCash = 0
> StoryCharacters:add_imgui(function()
>     mCash, used = ImGui.SliderInt("Michael's Cash", mCash, 1, 2147483646)
>     out = "Michael's cash set to $"..tostring(mCash)
>     if used then
>         STATS.STAT_SET_INT(joaat("SP0_TOTAL_CASH"), mCash, true)
>         gui.show_message('Story Mode Cash Updated!', out)
>     end
> end)
> 
> fCash = 0
> StoryCharacters:add_imgui(function()
>     fCash, used = ImGui.SliderInt("Franklin's Cash", fCash, 1, 2147483646)
>     out = "Franklins's cash set to $"..tostring(fCash)
>     if used then
>         STATS.STAT_SET_INT(joaat("SP1_TOTAL_CASH"), fCash, true)
>         gui.show_message('Story Mode Cash Updated!', out)
>     end
> end)
> 
> tCash = 0
> StoryCharacters:add_imgui(function()
>     tCash, used = ImGui.SliderInt("Trevor's Cash", tCash, 1, 2147483646)
>     out = "Trevor's cash set to $"..tostring(tCash)
>     if used then
>         STATS.STAT_SET_INT(joaat("SP2_TOTAL_CASH"), tCash, true)
>         gui.show_message('Story Mode Cash Updated!', out)
>     end
> end)
> StoryCharacters:add_separator()
> mStats = 0
> StoryCharacters:add_imgui(function()
>     mStats, used = ImGui.SliderInt("Michael's Stats", mStats, 0, 100)
>     out = "Michael's Stats set to "..tostring(mStats).."/100"
>     if used then
>         STATS.STAT_SET_INT(joaat("SP0_SPECIAL_ABILITY"), mStats, true)
>         STATS.STAT_SET_INT(joaat("SP0_STAMINA"), mStats, true)
>         STATS.STAT_SET_INT(joaat("SP0_STRENGTH"), mStats, true)
>         STATS.STAT_SET_INT(joaat("SP0_LUNG_CAPACITY"), mStats, true)
>         STATS.STAT_SET_INT(joaat("SP0_WHEELIE_ABILITY"), mStats, true)
>         STATS.STAT_SET_INT(joaat("SP0_FLYING_ABILITY"), mStats, true)
>         STATS.STAT_SET_INT(joaat("SP0_SHOOTING_ABILITY"), mStats, true)
>         STATS.STAT_SET_INT(joaat("SP0_STEALTH_ABILITY"), mStats, true)
>         gui.show_message('Story Mode Stats Updated!', out)
>     end
> end)
> 
> fStats = 0
> StoryCharacters:add_imgui(function()
>     fStats, used = ImGui.SliderInt("Franklin's Stats", fStats, 0, 100)
>     out = "Franklin's Stats set to "..tostring(fStats).."/100"
>     if used then
>         STATS.STAT_SET_INT(joaat("SP1_SPECIAL_ABILITY"), fStats, true)
>         STATS.STAT_SET_INT(joaat("SP1_STAMINA"), fStats, true)
>         STATS.STAT_SET_INT(joaat("SP1_STRENGTH"), fStats, true)
>         STATS.STAT_SET_INT(joaat("SP1_LUNG_CAPACITY"), fStats, true)
>         STATS.STAT_SET_INT(joaat("SP1_WHEELIE_ABILITY"), fStats, true)
>         STATS.STAT_SET_INT(joaat("SP1_FLYING_ABILITY"), fStats, true)
>         STATS.STAT_SET_INT(joaat("SP1_SHOOTING_ABILITY"), fStats, true)
>         STATS.STAT_SET_INT(joaat("SP1_STEALTH_ABILITY"), fStats, true)
>         gui.show_message('Story Mode Stats Updated!', out)
>     end
> end)
> 
> tStats = 0
> StoryCharacters:add_imgui(function()
>     tStats, used = ImGui.SliderInt("Trevor's Stats", tStats, 0, 100)
>     out = "Trevor's Stats set to "..tostring(tStats).."/100"
>     if used then
>         STATS.STAT_SET_INT(joaat("SP2_SPECIAL_ABILITY"), tStats, true)
>         STATS.STAT_SET_INT(joaat("SP2_STAMINA"), tStats, true)
>         STATS.STAT_SET_INT(joaat("SP2_STRENGTH"), tStats, true)
>         STATS.STAT_SET_INT(joaat("SP2_LUNG_CAPACITY"), tStats, true)
>         STATS.STAT_SET_INT(joaat("SP2_WHEELIE_ABILITY"), tStats, true)
>         STATS.STAT_SET_INT(joaat("SP2_FLYING_ABILITY"), tStats, true)
>         STATS.STAT_SET_INT(joaat("SP2_SHOOTING_ABILITY"), tStats, true)
>         STATS.STAT_SET_INT(joaat("SP2_STEALTH_ABILITY"), tStats, true)
>         gui.show_message('Story Mode Stats Updated!', out)
>     end
> end)`
> ```
> 
> The money option is a slider to set the amount of money for each SP character, rather than just adding 1 million here and there and also SP stats sliders. Feel free to change this all to your liking, probably alot of unnecessary extra code since this does not have a SP switch like the current script you provided has.

It's clean work fr + I did it in another way like it gets which SP Is On With calling SPX function same as MPX https://github.com/YimMenu-Lua/Utimate-Menu

**Comment by Deadlineem** [comment]
> > From Extras Addon to you
> > `
> > ```
> > mCash = 0
> > StoryCharacters:add_imgui(function()
> >     mCash, used = ImGui.SliderInt("Michael's Cash", mCash, 1, 2147483646)
> >     out = "Michael's cash set to $"..tostring(mCash)
> >     if used then
> >         STATS.STAT_SET_INT(joaat("SP0_TOTAL_CASH"), mCash, true)
> >         gui.show_message('Story Mode Cash Updated!', out)
> >     end
> > end)
> > 
> > fCash = 0
> > StoryCharacters:add_imgui(function()
> >     fCash, used = ImGui.SliderInt("Franklin's Cash", fCash, 1, 2147483646)
> >     out = "Franklins's cash set to $"..tostring(fCash)
> >     if used then
> >         STATS.STAT_SET_INT(joaat("SP1_TOTAL_CASH"), fCash, true)
> >         gui.show_message('Story Mode Cash Updated!', out)
> >     end
> > end)
> > 
> > tCash = 0
> > StoryCharacters:add_imgui(function()
> >     tCash, used = ImGui.SliderInt("Trevor's Cash", tCash, 1, 2147483646)
> >     out = "Trevor's cash set to $"..tostring(tCash)
> >     if used then
> >         STATS.STAT_SET_INT(joaat("SP2_TOTAL_CASH"), tCash, true)
> >         gui.show_message('Story Mode Cash Updated!', out)
> >     end
> > end)
> > StoryCharacters:add_separator()
> > mStats = 0
> > StoryCharacters:add_imgui(function()
> >     mStats, used = ImGui.SliderInt("Michael's Stats", mStats, 0, 100)
> >     out = "Michael's Stats set to "..tostring(mStats).."/100"
> >     if used then
> >         STATS.STAT_SET_INT(joaat("SP0_SPECIAL_ABILITY"), mStats, true)
> >         STATS.STAT_SET_INT(joaat("SP0_STAMINA"), mStats, true)
> >         STATS.STAT_SET_INT(joaat("SP0_STRENGTH"), mStats, true)
> >         STATS.STAT_SET_INT(joaat("SP0_LUNG_CAPACITY"), mStats, true)
> >         STATS.STAT_SET_INT(joaat("SP0_WHEELIE_ABILITY"), mStats, true)
> >         STATS.STAT_SET_INT(joaat("SP0_FLYING_ABILITY"), mStats, true)
> >         STATS.STAT_SET_INT(joaat("SP0_SHOOTING_ABILITY"), mStats, true)
> >         STATS.STAT_SET_INT(joaat("SP0_STEALTH_ABILITY"), mStats, true)
> >         gui.show_message('Story Mode Stats Updated!', out)
> >     end
> > end)
> > 
> > fStats = 0
> > StoryCharacters:add_imgui(function()
> >     fStats, used = ImGui.SliderInt("Franklin's Stats", fStats, 0, 100)
> >     out = "Franklin's Stats set to "..tostring(fStats).."/100"
> >     if used then
> >         STATS.STAT_SET_INT(joaat("SP1_SPECIAL_ABILITY"), fStats, true)
> >         STATS.STAT_SET_INT(joaat("SP1_STAMINA"), fStats, true)
> >         STATS.STAT_SET_INT(joaat("SP1_STRENGTH"), fStats, true)
> >         STATS.STAT_SET_INT(joaat("SP1_LUNG_CAPACITY"), fStats, true)
> >         STATS.STAT_SET_INT(joaat("SP1_WHEELIE_ABILITY"), fStats, true)
> >         STATS.STAT_SET_INT(joaat("SP1_FLYING_ABILITY"), fStats, true)
> >         STATS.STAT_SET_INT(joaat("SP1_SHOOTING_ABILITY"), fStats, true)
> >         STATS.STAT_SET_INT(joaat("SP1_STEALTH_ABILITY"), fStats, true)
> >         gui.show_message('Story Mode Stats Updated!', out)
> >     end
> > end)
> > 
> > tStats = 0
> > StoryCharacters:add_imgui(function()
> >     tStats, used = ImGui.SliderInt("Trevor's Stats", tStats, 0, 100)
> >     out = "Trevor's Stats set to "..tostring(tStats).."/100"
> >     if used then
> >         STATS.STAT_SET_INT(joaat("SP2_SPECIAL_ABILITY"), tStats, true)
> >         STATS.STAT_SET_INT(joaat("SP2_STAMINA"), tStats, true)
> >         STATS.STAT_SET_INT(joaat("SP2_STRENGTH"), tStats, true)
> >         STATS.STAT_SET_INT(joaat("SP2_LUNG_CAPACITY"), tStats, true)
> >         STATS.STAT_SET_INT(joaat("SP2_WHEELIE_ABILITY"), tStats, true)
> >         STATS.STAT_SET_INT(joaat("SP2_FLYING_ABILITY"), tStats, true)
> >         STATS.STAT_SET_INT(joaat("SP2_SHOOTING_ABILITY"), tStats, true)
> >         STATS.STAT_SET_INT(joaat("SP2_STEALTH_ABILITY"), tStats, true)
> >         gui.show_message('Story Mode Stats Updated!', out)
> >     end
> > end)`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The money option is a slider to set the amount of money for each SP character, rather than just adding 1 million here and there and also SP stats sliders. Feel free to change this all to your liking, probably alot of unnecessary extra code since this does not have a SP switch like the current script you provided has.
> 
> It's clean work fr + I did it in another way like it gets which SP Is On With calling SPX function same as MPX https://github.com/YimMenu-Lua/Utimate-Menu

Precisely, thats the only thing i didnt do was add the SPX switch similar to the one you used in UM for multiplayer characters.  Back in the times i didnt know anything about lua lmao

**Comment by L7NEG** [comment]
> > > From Extras Addon to you
> > > `
> > > ```
> > > mCash = 0
> > > StoryCharacters:add_imgui(function()
> > >     mCash, used = ImGui.SliderInt("Michael's Cash", mCash, 1, 2147483646)
> > >     out = "Michael's cash set to $"..tostring(mCash)
> > >     if used then
> > >         STATS.STAT_SET_INT(joaat("SP0_TOTAL_CASH"), mCash, true)
> > >         gui.show_message('Story Mode Cash Updated!', out)
> > >     end
> > > end)
> > > 
> > > fCash = 0
> > > StoryCharacters:add_imgui(function()
> > >     fCash, used = ImGui.SliderInt("Franklin's Cash", fCash, 1, 2147483646)
> > >     out = "Franklins's cash set to $"..tostring(fCash)
> > >     if used then
> > >         STATS.STAT_SET_INT(joaat("SP1_TOTAL_CASH"), fCash, true)
> > >         gui.show_message('Story Mode Cash Updated!', out)
> > >     end
> > > end)
> > > 
> > > tCash = 0
> > > StoryCharacters:add_imgui(function()
> > >     tCash, used = ImGui.SliderInt("Trevor's Cash", tCash, 1, 2147483646)
> > >     out = "Trevor's cash set to $"..tostring(tCash)
> > >     if used then
> > >         STATS.STAT_SET_INT(joaat("SP2_TOTAL_CASH"), tCash, true)
> > >         gui.show_message('Story Mode Cash Updated!', out)
> > >     end
> > > end)
> > > StoryCharacters:add_separator()
> > > mStats = 0
> > > StoryCharacters:add_imgui(function()
> > >     mStats, used = ImGui.SliderInt("Michael's Stats", mStats, 0, 100)
> > >     out = "Michael's Stats set to "..tostring(mStats).."/100"
> > >     if used then
> > >         STATS.STAT_SET_INT(joaat("SP0_SPECIAL_ABILITY"), mStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP0_STAMINA"), mStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP0_STRENGTH"), mStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP0_LUNG_CAPACITY"), mStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP0_WHEELIE_ABILITY"), mStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP0_FLYING_ABILITY"), mStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP0_SHOOTING_ABILITY"), mStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP0_STEALTH_ABILITY"), mStats, true)
> > >         gui.show_message('Story Mode Stats Updated!', out)
> > >     end
> > > end)
> > > 
> > > fStats = 0
> > > StoryCharacters:add_imgui(function()
> > >     fStats, used = ImGui.SliderInt("Franklin's Stats", fStats, 0, 100)
> > >     out = "Franklin's Stats set to "..tostring(fStats).."/100"
> > >     if used then
> > >         STATS.STAT_SET_INT(joaat("SP1_SPECIAL_ABILITY"), fStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP1_STAMINA"), fStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP1_STRENGTH"), fStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP1_LUNG_CAPACITY"), fStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP1_WHEELIE_ABILITY"), fStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP1_FLYING_ABILITY"), fStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP1_SHOOTING_ABILITY"), fStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP1_STEALTH_ABILITY"), fStats, true)
> > >         gui.show_message('Story Mode Stats Updated!', out)
> > >     end
> > > end)
> > > 
> > > tStats = 0
> > > StoryCharacters:add_imgui(function()
> > >     tStats, used = ImGui.SliderInt("Trevor's Stats", tStats, 0, 100)
> > >     out = "Trevor's Stats set to "..tostring(tStats).."/100"
> > >     if used then
> > >         STATS.STAT_SET_INT(joaat("SP2_SPECIAL_ABILITY"), tStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP2_STAMINA"), tStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP2_STRENGTH"), tStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP2_LUNG_CAPACITY"), tStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP2_WHEELIE_ABILITY"), tStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP2_FLYING_ABILITY"), tStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP2_SHOOTING_ABILITY"), tStats, true)
> > >         STATS.STAT_SET_INT(joaat("SP2_STEALTH_ABILITY"), tStats, true)
> > >         gui.show_message('Story Mode Stats Updated!', out)
> > >     end
> > > end)`
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The money option is a slider to set the amount of money for each SP character, rather than just adding 1 million here and there and also SP stats sliders. Feel free to change this all to your liking, probably alot of unnecessary extra code since this does not have a SP switch like the current script you provided has.
> > 
> > 
> > It's clean work fr + I did it in another way like it gets which SP Is On With calling SPX function same as MPX https://github.com/YimMenu-Lua/Utimate-Menu
> 
> Precisely, thats the only thing i didnt do was add the SPX switch similar to the one you used in UM for multiplayer characters. Back in the times i didnt know anything about lua lmao

xD but now you are W fr

**Comment by Deadlineem** [comment]
> xD but now you are W fr

I dont try to be, im just learning as I go.  My main focus and top priority is to bring shame to these paid menus and help the community

**Comment by gir489returns** [comment]
You just posted a script that does the same thing I'm already doing, what's the point? Also stop shilling your faggoty skidded ultimate menu.

**Comment by L7NEG** [comment]
> You just posted a script that does the same thing I'm already doing, what's the point? Also stop shilling your faggoty skidded ultimate menu.

ɪ ᴡɪʟʟ ꜱᴡɪɴɢ ᴍʏ ʙᴀʟʟꜱ ᴀᴄʀᴏꜱꜱ ʏᴏ ꜰᴀᴄᴇ ʟɪᴋᴇ ᴀ ɢʀᴀɴᴅꜰᴀᴛʜᴇʀ ᴄʟᴏᴄᴋ 🕰️🙏🏻 ᴅᴏɴ’ᴛ ᴇᴠᴇʀ ʟᴇᴛ ᴍᴇ ᴄᴀᴛᴄʜ ᴜ ᴄᴏᴍᴍᴇɴᴛɪɴɢ ᴀɢᴀɪɴ ʟɪʟ kid go cry with your skidded trash single player Menu some where else lmao crediting a kid to tell me I'm a skid is insane fr @lhwe

**Comment by L7NEG** [comment]
Imagine saying a one who gives credits to original author is a skid lmao Is insane xD

**Comment by L7NEG** [comment]
And I forgot to say you are a retarded faggot kid
